name: front
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=3.1.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  desktop_window: any
  flutter_dotenv: ^5.0.2
  http: any
  shared_preferences: ^2.0.6
  provider: any
  color_blindness : any
  random_color_scheme: any
  url_launcher: any
  flutter_svg: ^0.22.0 # Assurez-vous d'utiliser la version appropriée
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/window_size
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  assets:
    - .env
    - assets/logo_waterhub.svg
    - assets/logo.png
    - assets/1697310931old-man-7b.svg
  uses-material-design: true

